//@MySpot.Api_HostAddress = http://localhost:5000
@url = http://localhost:5000
@reservationId = 6a9e1471-5506-4b55-bdba-5c486ddd75fa
@parkingSpotId = 00000000-0000-0000-0000-000000000001


###
GET {{url}}
###
GET {{url}}/reservations

###
GET {{url}}/reservations/{{reservationId}}
###
POST {{url}}/reservations
Content-Type: application/json

{
    "parkingSpotId": "{{parkingSpotId}}",
    "employeeName": "John Doe",
    "licensePlate": "XYZ123",
    "date": "2024-10-23"
}

###
PUT {{url}}/reservations/{{reservationId}}
Content-Type: application/json
{
    "licensePlate": "XYZ1234"
}

###
DELETE {{url}}/reservations/{{reservationId}}