//@MySpot.Api_HostAddress = http://localhost:5000
@url = http://localhost:5000
@reservationId = b21d1c76-6890-452d-8151-365b1c538b03
@parkingSpotId = 00000000-0000-0000-0000-000000000003


###
GET {{url}}/parking-spots

###
POST {{url}}/parking-spots/{{parkingSpotId}}/reservations/vehicle
Content-Type: application/json
{
    "employeeName": "janek Doe",
    "licensePlate": "XYZ1235",
    "capacity": 1,
    "date": "2024-11-08"
}
###
POST {{url}}/parking-spots/reservations/cleaning
Content-Type: application/json
{
    "date": "2024-11-07"
}

###
PUT {{url}}/parking-spots/reservations/{{reservationId}}
Content-Type: application/json
{
    "licensePlate": "XYZ98"
}

###
DELETE {{url}}/parking-spots/reservations/{{reservationId}}