services:
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8080:80
    depends_on:
      - postgres
  
  myspot-api:
    build:
      context: ./src/
      dockerfile: MySpot.Api/Dockerfile  
    ports:
      - "8081:80"
    depends_on:
      - postgres

volumes:
  postgres:
    driver: local
